url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: PyLadies Natal
email: deboraazevedoo@gmail.com
description: "Site oficial do PyLadies Natal."


# Team names, titles and social links
people:
- name: Clara Nobre
  pic: clara
  position: Cofundadora do PyLadies Brasil/Natal
  social:
    - title: twitter
      url: https://twitter.com/_claranobre
    - title: facebook
      url: https://www.facebook.com/claranobre


- name: Débora Azevedo
  pic: debora
  position: Confudadora PyLadies Natal
  social:
    - title: twitter
      url: https://twitter.com/pydebb
    - title: facebook
      url: https://www.facebook.com/debora.azevedoo


- name: Gabi Cavalcante
  pic: gabi
  position: Cofundadora do PyLadies Brasil/Natal
  social:
    - title: twitter
      url: https://twitter.com/_gabiCavalcante
    - title: facebook
      url: https://www.facebook.com/gabi.cavalcante.silva


- name: Késsia Castro
  pic: kessia
  position: Colaboradora do PyLadies Natal
  social:
    - title: twitter
      url: https://twitter.com/kessiacastro
    - title: facebook
      url: https://www.facebook.com/kessiacastro


- name: Monnaliza Medeiros
  pic: mona
  position: Colaboradora do PyLadies Natal
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/monnalizadm
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/PyladiesNatal
  - title: facebook
    url: https://www.facebook.com/PyLadiesNatal/
  - title: github
    url: https://github.com/PyLadiesNatal

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
